// This file is part of Kuira Wallet.
// Copyright (C) 2025 Kuira Wallet
// SPDX-License-Identifier: Apache-2.0

package com.midnight.kuira.core.crypto.bip39

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Compatibility tests against official Midnight SDK (@scure/bip39).
 *
 * These tests verify that our BIP-39 implementation produces IDENTICAL
 * outputs to the official Midnight wallet SDK for the same inputs.
 *
 * **CRITICAL:** If these tests fail, wallets generated in Kuira cannot
 * be restored in Lace (official Midnight wallet) and vice versa.
 *
 * Test vectors extracted from:
 * - `/Users/norman/Development/midnight/MidnightWasmTest/test-zswap-official.mjs`
 * - Using @scure/bip39 (Midnight's BIP-39 library)
 * - Using @midnight-ntwrk/wallet-sdk-hd (Midnight's HD wallet)
 *
 * **Verification Date:** 2026-01-11
 * **Tested Against:** @scure/bip39 v1.5.4
 */
class BIP39MidnightCompatibilityTest {

    companion object {
        /**
         * Official Midnight test mnemonic (24 words).
         * Source: Midnight SDK test (test-full-midnight-flow.mjs)
         * Verified Date: 2026-01-11
         */
        private const val MIDNIGHT_TEST_MNEMONIC =
            "nut admit smart cake pet describe mirror result dinosaur math tail barrel " +
            "energy solar sound relief must kid right legal future pelican aware bachelor"

        /**
         * Expected seed with EMPTY passphrase (Midnight default).
         *
         * Generated by official Midnight SDK:
         * - @scure/bip39 v1.5.4 (used by @midnight-ntwrk/wallet-sdk-hd)
         * - mnemonicToSeed(mnemonic, '', wordlist)
         *
         * Verified Date: 2026-01-11
         */
        private const val EXPECTED_SEED_EMPTY_PASSPHRASE =
            "3397b06b3e151629bf24d49f5b1bbd91316346778edb651d016a2fdb59a98e8d" +
            "e7c7be6324de98d2dbab386300c12842ae2456767aa5807ef50d13cf108b9ece"

        /**
         * Expected seed with "TREZOR" passphrase (BIP-39 standard test vector).
         *
         * Generated by official Midnight SDK:
         * - @scure/bip39 v1.5.4
         * - mnemonicToSeed(mnemonic, 'TREZOR', wordlist)
         *
         * Verified Date: 2026-01-11
         */
        private const val EXPECTED_SEED_TREZOR_PASSPHRASE =
            "91496f149c964ad5a2c75ed11e2b575a206198341cc05ad6a2e3ee5dd3f96dd1" +
            "99fb417af4fafc52b2f4f29bdd13525111325b1c90e3f18a0d75673647d7fd85"

        /**
         * Expected BIP-32 derived keys for future HDWallet testing.
         * These are saved here but will be tested when we implement HDWallet.kt
         *
         * Generated by official Midnight SDK:
         * - @midnight-ntwrk/wallet-sdk-hd (which uses @scure/bip32)
         * - HDWallet.fromSeed(seed).selectAccount(0).selectRole(role).deriveKeyAt(index)
         *
         * Verified Date: 2026-01-11
         */
        @Suppress("unused") // Will be used when implementing HDWallet
        private object ExpectedBIP32Keys {
            // m/44'/2400'/0'/0/0 (NightExternal #0)
            const val NIGHT_EXTERNAL_0 = "0e1d589e6833e42e61a0a639419dc4cf02caafd0afc0e17b5769cf3c9fc7c699"

            // m/44'/2400'/0'/0/1 (NightExternal #1)
            const val NIGHT_EXTERNAL_1 = "d6e5488bca677c9e97f173f555c181f50dc67c5948d6fc4c76c8c1bd2f0cdae9"

            // m/44'/2400'/0'/0/2 (NightExternal #2)
            const val NIGHT_EXTERNAL_2 = "7572bcabe36636e1a8f520d5511bff8b2e7c1c90176be493aebc4ecca74130ae"

            // m/44'/2400'/0'/3/0 (Zswap #0)
            const val ZSWAP_0 = "4da0c7b3dd5118acda8038a6be0ebc87e67199f531f703f35cde21858b95f546"
        }
    }

    @Test
    fun `given Midnight test mnemonic when deriving seed with empty passphrase then matches Midnight SDK output`() {
        // Given - Official Midnight test mnemonic
        val mnemonic = MIDNIGHT_TEST_MNEMONIC

        // When - Derive seed with empty passphrase (Midnight default)
        val actualSeed = BIP39.mnemonicToSeed(mnemonic, passphrase = "")

        // Then - Must match Midnight SDK output EXACTLY
        assertEquals(
            "Seed must match official Midnight SDK (@scure/bip39) output",
            EXPECTED_SEED_EMPTY_PASSPHRASE,
            actualSeed.toHex()
        )
    }

    @Test
    fun `given Midnight test mnemonic when deriving seed with TREZOR passphrase then matches Midnight SDK output`() {
        // Given - Official Midnight test mnemonic
        val mnemonic = MIDNIGHT_TEST_MNEMONIC

        // When - Derive seed with "TREZOR" passphrase (BIP-39 standard)
        val actualSeed = BIP39.mnemonicToSeed(mnemonic, passphrase = "TREZOR")

        // Then - Must match Midnight SDK output EXACTLY
        assertEquals(
            "Seed must match official Midnight SDK (@scure/bip39) output",
            EXPECTED_SEED_TREZOR_PASSPHRASE,
            actualSeed.toHex()
        )
    }

    @Test
    fun `given Midnight test mnemonic when validating then returns true`() {
        // Given - Official Midnight test mnemonic
        val mnemonic = MIDNIGHT_TEST_MNEMONIC

        // When - Validate mnemonic
        val isValid = BIP39.validateMnemonic(mnemonic)

        // Then - Must be valid (same as Midnight SDK)
        assertEquals(
            "Midnight test mnemonic must be valid",
            true,
            isValid
        )
    }

    @Test
    fun `given Midnight test mnemonic when counting words then has 24 words`() {
        // Given - Official Midnight test mnemonic
        val mnemonic = MIDNIGHT_TEST_MNEMONIC

        // When - Count words
        val wordCount = mnemonic.split(" ").size

        // Then - Must have 24 words
        assertEquals(
            "Midnight test mnemonic must have 24 words",
            24,
            wordCount
        )
    }

    @Test
    fun `given different passphrases when deriving seeds then produces different outputs`() {
        // Given - Same mnemonic, different passphrases
        val mnemonic = MIDNIGHT_TEST_MNEMONIC

        // When - Derive seeds with different passphrases
        val seedEmpty = BIP39.mnemonicToSeed(mnemonic, passphrase = "")
        val seedTrezor = BIP39.mnemonicToSeed(mnemonic, passphrase = "TREZOR")

        // Then - Seeds must be different
        assert(seedEmpty.toHex() != seedTrezor.toHex()) {
            "Different passphrases must produce different seeds"
        }

        // And - Both must match expected values
        assertEquals(EXPECTED_SEED_EMPTY_PASSPHRASE, seedEmpty.toHex())
        assertEquals(EXPECTED_SEED_TREZOR_PASSPHRASE, seedTrezor.toHex())
    }

    /**
     * Extension function to convert ByteArray to hex string.
     */
    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
